const router = require('express').Router();
const modulesRoutes = require('./moduleRoutes/modulesRoutes');
const categoriesRoutes = require('./moduleRoutes/categoriesRoutes');
const subCategoriesRoutes = require('./moduleRoutes/subCategoriesRoutes');
const moduleSubCategoryRoutes = require('./moduleRoutes/moduleSubCategoryRoutes');
const packagesRoutes = require('./moduleRoutes/packagesRoutes');
const alertsRoutes = require('./alertsRoutes');
const lettersRoutes = require('./moduleRoutes/lettersRoutes');  
const moduleLetterRoutes = require('./moduleRoutes/moduleLetterRoutes');
const rolesRoutes = require('./userRoutes/rolesRoutes');
const userRoutes = require('./userRoutes/userRoutes');
const authRoutes = require('./userRoutes/authRoutes');
const countriesRoutes = require('./userRoutes/countriesRoutes');
const citiesRoutes = require('./userRoutes/citiesRoutes');
const organizationsRoutes = require('./userRoutes/organizationsRoutes');
const adminPermissionsRoutes = require('./userRoutes/adminPermissionsRoutes');
const quizScoreRoutes = require('./moduleRoutes/quizScoreRoutes');
const downloadsroutes = require('./moduleRoutes/downloadsRoutes')
const leaderboard = require('./moduleRoutes/leaderboard');
const googleAPIKeyRoute = require('./googleAPIKeyRoute');
const specializationsRoutes = require('./moduleRoutes/specializationsRoutes');
const emailRoutes = require('./emailRoutes');
const examSessionsRoutes = require('./examRoutes/examSessionsRoutes');
const examRoutes = require('./examRoutes/examsRoutes');
const adminExamRoutes = require('./examRoutes/adminExamRoutes');
const adminOrganizationsRoutes = require('./adminRoutes/adminOrganizationsRoutes');
const cmeCertificateRoutes = require('./certificateRoutes/cmeCertificateRoutes');

router.use('/modules', modulesRoutes);
router.use('/categories', categoriesRoutes);
router.use('/subCategories', subCategoriesRoutes);
router.use('/modules-to-subCategories', moduleSubCategoryRoutes);
router.use('/subCategories-to-modules', moduleSubCategoryRoutes);
router.use('/packages', packagesRoutes);
router.use('/alerts', alertsRoutes);
router.use('/letters', lettersRoutes);
router.use('/modules-to-letters', moduleLetterRoutes);
router.use('/letters-to-modules', moduleLetterRoutes);
router.use('/roles', rolesRoutes);
router.use('/users', userRoutes);
router.use('/auth', authRoutes);
router.use('/countries', countriesRoutes);
router.use('/cities', citiesRoutes);
router.use('/organizations', organizationsRoutes);
router.use('/admin-permissions', adminPermissionsRoutes);
router.use('/quiz-scores', quizScoreRoutes);
router.use('/api/downloads', downloadsroutes);
router.use('/leaderboard', leaderboard);
router.use('/api/googleAPIKey', googleAPIKeyRoute);
router.use('/api/specializations', specializationsRoutes);
router.use('/email', emailRoutes);
router.use('/exam-sessions', examSessionsRoutes);
router.use('/exams', examRoutes);
router.use('/api/admin/exams', adminExamRoutes);
router.use('/api/admin/organizations', adminOrganizationsRoutes);
router.use('/certificates', cmeCertificateRoutes);

module.exports = router;
