const { SubCategories } = require('../models');
const Modules = require('../models/modules');

const modulesData = [
    {
        //id: 1,
        name: 'Women\'s Health: Skin and hair health',
        description: 'WiRED\'s medical team is currently rewriting the material for this series. Please return to this page for future updates',
        letters: 'W',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
        SubCategories: [],
    },
    {
        //id: 2,
        name: 'Acne',
        description: '',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 1,
    },    {
        //id: 3,
        name: 'HIV/AIDS: Caring for someone with AIDS at home',
        description: '',
        letters: 'H',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 4,
        name: 'Acquired Immunodeficiency Syndrome',
        description: '',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 3,
    },
    {
        //id: 5,
        name: 'Bronchitis',
        description: 'A Guide for General Audiences: This module is specifically targeted to general audiences and contains information about the causes, symptoms, diagnosis and treatment of bronchitis.',
        letters: 'B',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 6,
        name: 'Acute Bronchitis',
        description: '',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 5,
    },
    {
        //id: 7,
        name: 'Upper respiratory tract infection; Ear, nose and throat (ENT)',
        description: '',
        letters: 'U',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 8,
        name: 'Adenoidectomy ',
        description: '',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 7,
    },
    {
        //id: 9,
        name: 'Adenoids',
        description: '',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 7,
    },
    {
        //id: 10,
        name: 'Seminar in attention deficit hyperactivity disorder (ADHD)',
        description: '',
        letters: 'S',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 11,
        name: 'ADHD',
        description: '',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 10,
    },
    {
        //id: 12,
        name: 'HIV/AIDS: Basic information',
        description: '',
        letters: 'H',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 13,
        name: 'AIDS',
        description: '',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 12,
    },
    {
        //id: 14,
        name: 'Air Pollution',
        description: '',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 15,
        name: 'Airborne Diseases',
        description: '',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 16,
        name: 'Alcohol - Quitting Alcohol for Health',
        description: '',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 17,
        name: 'Upper respiratory tract infection',
        description: '',
        letters: 'U',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 18,
        name: 'Allergy',
        description: '',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 17,
    },
    {
        //id: 19,
        name: 'Alzheimer\'s disease',
        description: '',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 20,
        name: 'Anatomy Series',
        description: '',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 21,
        name: 'Anatomy',
        description: '',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 20,
    },
    {
        //id: 22,
        name: 'Anemia',
        description: '',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 23,
        name: 'Sickle Cell Disease',
        description: '',
        letters: 'S',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 24,
        name: 'Anemia (Sickle Cell)',
        description: '',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 23,
    },
    {
        //id: 25,
        name: 'Mental Health: Depression',
        description: '',
        letters: 'M',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 26,
        name: 'Antidepressants',
        description: '',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 25,
    },
    {
        //id: 27,
        name: 'High blood pressure (hypertension)',
        description: '',
        letters: 'H',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 28,
        name: 'Antihypertensive Medicines',
        description: '',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 27,
    },
    {
        //id: 29,
        name: 'Antiretroviral therapy for adults and children',
        description: '',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 30,
        name: 'Seminar in anxiety disorders',
        description: '',
        letters: 'S',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 31,
        name: 'Anxiety',
        description: '',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 30,
    },
    {
        //id: 32,
        name: 'Rheumatic Heart Disease Training Series',
        description: '',
        letters: 'R',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 33,
        name: 'Aortic Stenosis',
        description: '',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 32,
    },
    {
        //id: 34,
        name: 'Meningitis',
        description: '',
        letters: 'M',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 35,
        name: 'Arachnoiditis',
        description: '',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 34,
    },
    {
        //id: 36,
        name: 'Arthritis',
        description: '',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 37,
        name: 'Aseptic Meningitis',
        description: '',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 34,
    },
    {
        //id: 38,
        name: 'Asthma',
        description: '',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 39,
        name: 'Eye problems',
        description: '',
        letters: 'E',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 40,
        name: 'Astigmatism',
        description: '',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 39,
    },
    {
        //id: 41,
        name: 'Fungal infections',
        description: '',
        letters: 'F',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 42,
        name: 'Athlete\'s Foot',
        description: '',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 41,
    },
    {
        //id: 43,
        name: 'Attention Deficit Hyperactivity Disorder',
        description: '',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 10,
    },
    {
        //id: 44,
        name: 'Autoimmune Diseases, Introduction',
        description: 'This module describes the immune system and how autoimmune diseases can affect almost any part of the body, such as the heart, brain, nerves, muscles, eyes and kidneys. The training covers the causes of autoimmune diseases, their signs, symptoms and treatment and lists common types of these illnesses.',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },



];

const seedModules = async () => {
    try {
        const count = await Modules.count(); 
        if (count === 0) {
            await Modules.bulkCreate(modulesData);
            console.log('Modules seeded successfully!');
        } else {
            console.log('Modules table already has data, skipping seeding.');
        }
    } catch (error) {
        console.error('Error seeding modules:', error);
    }
};

module.exports = seedModules;