const { SubCategories } = require('../models');
const Modules = require('../models/modules');

const modulesData = [
    {
        //id: 1,
        name: 'Women\'s Health: Skin and hair health',
        description: 'WiRED\'s medical team is currently rewriting the material for this series. Please return to this page for future updates',
        letters: 'W',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
        SubCategories: [],
    },
    {
        //id: 2,
        name: 'Acne',
        description: '',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 1,
    },    {
        //id: 3,
        name: 'HIV/AIDS: Caring for someone with AIDS at home',
        description: '',
        letters: 'H',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 4,
        name: 'Acquired Immunodeficiency Syndrome',
        description: '',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 3,
    },
    {
        //id: 5,
        name: 'Bronchitis',
        description: 'A Guide for General Audiences: This module is specifically targeted to general audiences and contains information about the causes, symptoms, diagnosis and treatment of bronchitis.',
        letters: 'B',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 6,
        name: 'Acute Bronchitis',
        description: '',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 5,
    },
    {
        //id: 7,
        name: 'Upper respiratory tract infection; Ear, nose and throat (ENT)',
        description: '',
        letters: 'U',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 8,
        name: 'Adenoidectomy ',
        description: '',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 7,
    },
    {
        //id: 9,
        name: 'Adenoids',
        description: '',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 7,
    },
    {
        //id: 10,
        name: 'Seminar in attention deficit hyperactivity disorder (ADHD)',
        description: '',
        letters: 'S',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 11,
        name: 'ADHD',
        description: '',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 10,
    },
    {
        //id: 12,
        name: 'HIV/AIDS: Basic information',
        description: '',
        letters: 'H',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 13,
        name: 'AIDS',
        description: '',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 12,
    },
    {
        //id: 14,
        name: 'Air Pollution',
        description: '',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 15,
        name: 'Airborne Diseases',
        description: '',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 16,
        name: 'Alcohol - Quitting Alcohol for Health',
        description: '',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 17,
        name: 'Upper respiratory tract infection',
        description: '',
        letters: 'U',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 18,
        name: 'Allergy',
        description: '',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 17,
    },
    {
        //id: 19,
        name: 'Alzheimer\'s disease',
        description: '',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 20,
        name: 'Anatomy & Illness Fundamentals—Part 1 (Express module)',
        description: 'A Guide for Grass Roots Audiences: This module describes the circulatory, musculoskeletal, digestive, urinary and respiratory systems. The two main topics are healthy body functioning and unhealthy body functioning.',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 21,
        name: 'Anatomy & Illness Fundamentals—Part 2 (Express module)',
        description: 'A Guide for Grass Roots Audiences: This module describes the endocrine, lymphatic, immune, nervous and reproductive systems..',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 22,
        name: 'Anatomy & Illness Fundamentals—Part 3 (Express module)',
        description: 'A Guide for Grass Roots Audiences: This module describes infectious and non-infectious diseases.',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 23,
        name: 'Anatomía y Enfermedad Fundamentos—Parte 1 (Modulo Expreso) (Spanish)',
        description: '',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 24,
        name: 'Anatomía y Enfermedad Fundamentos—Parte 2 (Modulo Expreso) (Spanish)',
        description: '',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 25,
        name: 'Anatomía y Enfermedad Fundamentos—Parte 3 (Modulo Expreso) (Spanish)',
        description: '',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 26,
        name: 'Anemia',
        description: '',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 27,
        name: 'Sickle Cell Disease',
        description: '',
        letters: 'S',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 28,
        name: 'Anemia (Sickle Cell)',
        description: '',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 23,
    },
    {
        //id: 29,
        name: 'Mental Health: Depression',
        description: '',
        letters: 'M',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 30,
        name: 'Antidepressants',
        description: '',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 25,
    },
    {
        //id: 31,
        name: 'High blood pressure (hypertension)',
        description: '',
        letters: 'H',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 32,
        name: 'Antihypertensive Medicines',
        description: '',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 27,
    },
    {
        //id: 33,
        name: 'Antiretroviral therapy for adults and children',
        description: '',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 34,
        name: 'Seminar in anxiety disorders',
        description: '',
        letters: 'S',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 35,
        name: 'Anxiety',
        description: '',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 30,
    },
    {
        //id: 36,
        name: 'Rheumatic Heart Disease Training Series',
        description: '',
        letters: 'R',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 37,
        name: 'Aortic Stenosis',
        description: '',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 32,
    },
    {
        //id: 38,
        name: 'Meningitis',
        description: '',
        letters: 'M',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 39,
        name: 'Arachnoiditis',
        description: '',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 34,
    },
    {
        //id: 40,
        name: 'Arthritis',
        description: '',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 41,
        name: 'Aseptic Meningitis',
        description: '',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 34,
    },
    {
        //id: 42,
        name: 'Asthma',
        description: '',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 43,
        name: 'Eye problems',
        description: '',
        letters: 'E',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 44,
        name: 'Astigmatism',
        description: '',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 39,
    },
    {
        //id: 45,
        name: 'Fungal infections',
        description: '',
        letters: 'F',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 46,
        name: 'Athlete\'s Foot',
        description: '',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 41,
    },
    {
        //id: 47,
        name: 'Attention Deficit Hyperactivity Disorder',
        description: '',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 10,
    },
    {
        //id: 48,
        name: 'Autoimmune Diseases, Introduction',
        description: 'This module describes the immune system and how autoimmune diseases can affect almost any part of the body, such as the heart, brain, nerves, muscles, eyes and kidneys. The training covers the causes of autoimmune diseases, their signs, symptoms and treatment and lists common types of these illnesses.',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    // B
    {
        //id: 49,
        name: 'Maternal health and postnatal care',
        description: '',
        letters: 'M',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 50,
        name: 'Baby Blues',
        description: '',
        letters: 'B',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 49,
    },
    {
        //id: 51,
        name: 'Infant feeding',
        description: '',
        letters: 'I',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 52,
        name: 'Baby Care',
        description: '',
        letters: 'B',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 51,
    },
    {
        //id: 53,
        name: 'Infant health',
        description: '',
        letters: 'I',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 54,
        name: 'Baby Health Checkup',
        description: '',
        letters: 'B',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 53,
    },
    {
        //id: 55,
        name: 'Pain',
        description: '',
        letters: 'P',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 56,
        name: 'Back Pain',
        description: '',
        letters: 'B',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 55,
    },
    {
        //id: 57,
        name: 'First Aid: Bites and stings',
        description: '',
        letters: 'F',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 58,
        name: 'Bee Stings',
        description: '',
        letters: 'B',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 57,
    },
    {
        //id: 59,
        name: 'Before Pregnancy, Introduction to',
        description: '',
        letters: 'B',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 60,
        name: 'Benign Prostatic Hyperplasia',
        description: '',
        letters: 'B',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 61,
        name: 'Alcohol and substance abuse',
        description: '',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 62,
        name: 'Binge Drinking',
        description: '',
        letters: 'B',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 61,
    },
    {
        //id: 63,
        name: 'Biosand filters',
        description: '',
        letters: 'B',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 64,
        name: 'Seminar in bipolar disorder',
        description: '',
        letters: 'S',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 65,
        name: 'Bipolar Disorder',
        description: '',
        letters: 'B',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 64,
    },
    {
        //id: 66,
        name: 'Family planning',
        description: '',
        letters: 'F',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 67,
        name: 'Birth Control',
        description: '',
        letters: 'B',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 66,
    },
    {
        //id: 68,
        name: 'Birth Defects',
        description: '',
        letters: 'B',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 69,
        name: 'Urinary tract infections',
        description: '',
        letters: 'U',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 70,
        name: 'Bladder Infections',
        description: '',
        letters: 'B',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 69,
    },
    {
        //id: 71,
        name: 'Women\'s Health: Blood disorders',
        description: '',
        letters: 'W',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 72,
        name: 'Bleeding Disorders',
        description: '',
        letters: 'B',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 71,
    },
    {
        //id: 73,
        name: 'Blood Cells',
        description: '',
        letters: 'B',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 71,
    },
    {
        //id: 74,
        name: 'Blood Clots',
        description: '',
        letters: 'B',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 71,
    },
    {
        //id: 75,
        name: 'Blood Disorders',
        description: '',
        letters: 'B',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 71,
    },
 
    {
        //id: 76,
        name: 'Blood Pressure',
        description: '',
        letters: 'B',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 31,
    },
    {
        //id: 77,
        name: 'Blood Pressure Medicines',
        description: '',
        letters: 'B',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 31,
    },
    {
        //id: 78,
        name: 'Obesity',
        description: '',
        letters: 'O',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 79,
        name: 'BMI',
        description: '',
        letters: 'B',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 78,
    },
    {
        //id: 80,
        name: 'Body Weight',
        description: '',
        letters: 'B',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 78,
    },
    {
        //id: 81,
        name: 'Alternative Medicine: Introduction',
        description: '',
        letters: 'A',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 82,
        name: 'Botanicals',
        description: '',
        letters: 'B',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 81,
    },
    {
        //id: 83,
        name: 'Diarrhea, dehydration and ORT',
        description: '',
        letters: 'D',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 84,
        name: 'Bowel Movement',
        description: '',
        letters: 'B',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 83,
    },
    {
        //id: 85,
        name: 'Stroke',
        description: '',
        letters: 'S',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 86,
        name: 'Brain Attack',
        description: '',
        letters: 'B',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 85,
    },
    {
        //id: 87,
        name: 'Cancer: Breast',
        description: '',
        letters: 'C',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 88,
        name: 'Breast Cancer',
        description: '',
        letters: 'B',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 87,
    },
    {
        //id: 89,
        name: 'Breast Feeding',
        description: '',
        letters: 'B',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 51,
    },
    {
        //id: 90,
        name: 'First Aid: Fractures',
        description: '',
        letters: 'F',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 91,
        name: 'Broken Bones',
        description: '',
        letters: 'B',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 90,
    },
    {
        //id: 92,
        name: 'Bronchial Asthma',
        description: '',
        letters: 'B',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 42,
    },
    {
        //id: 93,
        name: 'Pneumonia',
        description: '',
        letters: 'P',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 94,
        name: 'Bronchopneumonia',
        description: '',
        letters: 'B',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 93,
    },
    {
        //id: 95,
        name: 'First Aid: Burns',
        description: '',
        letters: 'F',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 96,
        name: 'Burns',
        description: '',
        letters: 'B',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 95,
    },
    // C
    {
        //id: 97,
        name: 'CAM',
        description: '',
        letters: 'C',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 81,
    },
    {
        //id: 98,
        name: 'Women\'s Health: Cancer',
        description: '',
        letters: 'W',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 99,
        name: 'Cancer',
        description: '',
        letters: 'C',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 98,
    },
    {
        //id: 100,
        name: 'Introduction to Cancer - Part 1',
        description: '',
        letters: 'C',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 101,
        name: 'Introduction to Cancer - Part 2',
        description: '',
        letters: 'C',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 102,
        name: 'Introduction to Cancer - Part 3',
        description: '',
        letters: 'C',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 103,
        name: 'Bladder Cancer - Part 1',
        description: '',
        letters: 'B',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 104,
        name: 'Bladder Cancer - Part 2',
        description: '',
        letters: 'B',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 105,
        name: 'Brain tumors - Part 1',
        description: '',
        letters: 'B',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 106,
        name: 'Brain tumors - Part 2',
        description: '',
        letters: 'B',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 107,
        name: 'Cervical cancer - Part 1',
        description: '',
        letters: 'C',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 108,
        name: 'Cervical cancer - Part 2',
        description: '',
        letters: 'C',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 109,
        name: 'Colorectal cancer - Part 1',
        description: '',
        letters: 'C',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 110,
        name: 'Colorectal cancer - Part 2',
        description: '',
        letters: 'C',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 111,
        name: 'Hodgkin Lymphoma - Part 1',
        description: '',
        letters: 'H',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 112,
        name: 'Hodgkin Lymphoma - Part 2',
        description: '',
        letters: 'H',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 113,
        name: 'Kidney (Renal) Cancer',
        description: '',
        letters: 'K',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 114,
        name: 'Ovarian Cancer (Express module)',
        description: '',
        letters: 'O',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 115,
        name: 'Cáncer de Ovario (Modulo Expreso) (Spanish)',
        description: '',
        letters: 'C',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 116,
        name: 'Pancreatic cancer',
        description: '',
        letters: 'P',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 117,
        name: 'Prostate Cancer (Express Module)',
        description: '',
        letters: 'P',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 118,
        name: 'Cáncer de Próstata (Modulo Expreso) (Spanish)',
        description: '',
        letters: 'C',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 119,
        name: 'Breast cancer - Part 1',
        description: '',
        letters: 'B',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 120,
        name: 'Breast cancer - Part 2',
        description: '',
        letters: 'B',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 121,
        name: 'Breast cancer - Part 3',
        description: '',
        letters: 'B',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 122,
        name: 'Breast cancer - Part 4',
        description: '',
        letters: 'B',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 123,
        name: 'Lung cancer',
        description: '',
        letters: 'L',
        version: '1.0.0',
        is_downloadable: true,
        downloadLink: 'https://example.com/module1.zip',
        packageSize: null,
        redirect_module_id: null,
    },
    {
        //id: 124,
        name: 'Candidiasis',
        description: '',
        letters: 'C',
        version: '1.0.0',
        is_downloadable: false,
        downloadLink: '',
        packageSize: null,
        redirect_module_id: 45,
    },

];

const seedModules = async () => {
    try {
        const count = await Modules.count(); 
        if (count === 0) {
            await Modules.bulkCreate(modulesData);
            console.log('Modules seeded successfully!');
        } else {
            console.log('Modules table already has data, skipping seeding.');
        }
    } catch (error) {
        console.error('Error seeding modules:', error);
    }
};

module.exports = seedModules;